# Generated by Django 2.1.1 on 2019-02-16 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discordlink', models.CharField(max_length=150, null=True)),
                ('publiclink', models.BooleanField(default=False)),
                ('publicws', models.BooleanField(default=False)),
                ('publicmembers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relics', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CorpGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discordid', models.CharField(max_length=100)),
                ('publicprofile', models.BooleanField(default=False)),
                ('nextshipid', models.IntegerField(default=0)),
                ('timezone', models.CharField(default='UTC', max_length=120)),
                ('corp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp', to='main.Corporation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('level', models.IntegerField(default=1)),
                ('modules', models.TextField(default='{}')),
                ('rslevel', models.IntegerField(default=1)),
                ('influence', models.IntegerField(default=0)),
                ('bslevel', models.IntegerField(default=1)),
                ('fslevel', models.IntegerField(default=1)),
                ('tslevel', models.IntegerField(default=1)),
                ('creator', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('captain', models.BooleanField(default=False)),
                ('ships', models.TextField(default='[]')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Player')),
            ],
        ),
        migrations.CreateModel(
            name='WS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('opponentcorp', models.CharField(max_length=120)),
                ('score', models.IntegerField(default=0)),
                ('opponentscore', models.IntegerField(default=0)),
                ('start', models.DateTimeField()),
                ('comment', models.TextField(default='')),
                ('state', models.CharField(default='ws.state.future', max_length=120)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Corporation')),
            ],
        ),
        migrations.CreateModel(
            name='WSPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ships', models.TextField(default='[]')),
                ('dispos', models.TextField(default='{}')),
                ('update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.PlayerUpdate')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WS')),
            ],
        ),
    ]
