# Generated by Django 2.1.1 on 2019-02-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_playerupdate_groupadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpgroup',
            name='isgroup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='groupcreator',
            field=models.BooleanField(default=False),
        ),
    ]
