# Generated by Django 2.1.1 on 2019-02-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190216_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CorpGroup'),
        ),
    ]
