# Generated by Django 2.1.1 on 2019-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190218_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('operand1', models.CharField(max_length=150, null=True)),
                ('operand2', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('channel', models.CharField(max_length=150, null=True)),
                ('operand1', models.CharField(max_length=150, null=True)),
                ('operand2', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='discordid',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='language',
            field=models.CharField(default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='managementchannel',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='notifchannel',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporation',
            name='confirmedgroup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='confirmedcorp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='language',
            field=models.CharField(default='FR', max_length=2),
        ),
    ]
