# Generated by Django 2.1.1 on 2019-03-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190306_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpgroup',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='corporation',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='corporation',
            name='confirmedgroup',
        ),
        migrations.RemoveField(
            model_name='player',
            name='confirmedcorp',
        ),
        migrations.AddField(
            model_name='player',
            name='pendingcorp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Corporation'),
        ),
    ]
