# Generated by Django 2.1.1 on 2019-03-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190313_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotCommand',
        ),
        migrations.DeleteModel(
            name='BotOperation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='adminrole',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='memberrole',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='modorole',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='resporole',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporation',
            name='leadrole',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporation',
            name='memberrole',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporation',
            name='wsrole',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
