# Generated by Django 2.1.1 on 2019-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190313_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
