# Generated by Django 2.1.1 on 2019-03-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_player_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpgroup',
            name='commandmodules',
            field=models.TextField(default='{"help": true, "account": true}'),
        ),
    ]
