# Generated by Django 2.1.1 on 2019-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_corpgroup_commandmodules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='player',
            name='groupadmin',
        ),
        migrations.RemoveField(
            model_name='player',
            name='groupcreator',
        ),
        migrations.AddField(
            model_name='player',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='responsible',
            field=models.BooleanField(default=False),
        ),
    ]
