# Generated by Django 2.1.1 on 2019-03-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190314_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pendingroles',
            field=models.TextField(default='[false, false, false]'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pendingcorp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Corporation'),
        ),
    ]
