# Generated by Django 2.1.1 on 2019-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190314_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpgroup',
            name='commandmodules',
            field=models.TextField(default='["help", "account"]'),
        ),
    ]
