# Generated by Django 2.1.1 on 2019-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190315_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpgroup',
            name='publiclink',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='publicmembers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='publicws',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='publicprofile',
            field=models.BooleanField(default=True),
        ),
    ]
