# Generated by Django 2.1.1 on 2019-03-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190316_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerupdate',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Player'),
        ),
    ]
