# Generated by Django 2.1.1 on 2019-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190317_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ws',
            name='opponentcorp',
            field=models.CharField(default='???', max_length=120),
        ),
    ]
