# Generated by Django 2.1.1 on 2019-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190317_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpgroup',
            name='enable_leavenotif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='enable_welcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='private_welcome',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='welcome',
            field=models.TextField(default=''),
        ),
    ]
