# Generated by Django 2.1.1 on 2019-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_redstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpgroup',
            name='custom_commands',
            field=models.TextField(default='{}'),
        ),
    ]
