# Generated by Django 2.2 on 2019-04-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190402_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpgroup',
            name='adminrole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='discordid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='managementchannel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='memberrole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='modorole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='notifchannel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='resporole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='leadrole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='memberrole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='wsrole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='discordid',
            field=models.IntegerField(default=-1),
        ),
    ]
