# Generated by Django 2.2 on 2019-05-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190511_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerupdate',
            name='captain',
        ),
        migrations.AddField(
            model_name='ws',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Player'),
        ),
    ]
