# Generated by Django 2.2 on 2019-08-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190511_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpgroup',
            name='faqchannel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='faqcolor',
            field=models.CharField(default='#000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpgroup',
            name='faqnotifs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='commandmodules',
            field=models.TextField(default='["help", "account", "hadesstar"]'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('topics', models.TextField()),
                ('question', models.TextField()),
                ('answers', models.TextField(default='[]')),
                ('asker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Player')),
            ],
        ),
    ]
