# Generated by Django 2.2 on 2019-08-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190831_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
    ]
