# Generated by Django 2.2 on 2019-08-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190831_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpgroup',
            name='faqcolor',
        ),
    ]
