# Generated by Django 2.2 on 2019-08-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_corpgroup_faqcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpgroup',
            name='faqcolor',
            field=models.IntegerField(default=0),
        ),
    ]
