# Generated by Django 2.2 on 2019-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190908_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsplayer',
            name='losses',
            field=models.IntegerField(default=0),
        ),
    ]
