# Generated by Django 2.2 on 2019-09-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_wsplayer_losses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsplayer',
            name='losses',
        ),
        migrations.AddField(
            model_name='redstar',
            name='latestqueues',
            field=models.TextField(default='[-1, -1, -1, -1]'),
        ),
    ]
