# Generated by Django 2.2 on 2019-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190911_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpgroup',
            old_name='faqcolor',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='corpgroup',
            name='commandmodules',
            field=models.TextField(default='["help", "account", "hadesstar", "redstar", "whitestar", "management", "utilities", "faq"]'),
        ),
    ]
